### PR TITLE
fix bug where archive was being set to codename

### PR DESCRIPTION
**Pull request by jacksingleton**
At least on Debian Jessie, setting `archive` = `codename` is wrong and results security upgrades not being applied.

Not sure if this is a problem on Ubuntu as well.

### CODE REVIEW

**Comment by jnv** [comment]
Whoops, I think you are right. Could you please fix the README as well?

**Comment by jacksingleton** [comment]
Thanks for the quick reply!

Made the change in the README. (for Debian)

I don't have time to check on Ubuntu so I'm not sure if that needs to be changed as well.

**Comment by jnv** [comment]
Thanks! I'm offline this weekend, but I will try to merge and release this early next week.

**Comment by jnv** [comment]
Okay, I have squashed these commits into 83be977a637aac912b1a8f0650d29330b93144f9
Thanks!

**Pull request closed without merging**
