### PR TITLE
Moved configuration into a new file that doesn't overwrite default settings

### PR DESCRIPTION
**Pull request by colans**
See #32 for details.

### CODE REVIEW

**Comment by jnv** [comment]
This is awesome, thank you Colan! I would like to bundle this change along with other breaking changes into next major release, I will prepare a new branch and include your PR there.

**Comment by colans** [comment]
@jnv It's now been over a year.  Would you have some time to merge this, and ideally cut a new release on Galaxy?  Thanks!

**Comment by jnv** [comment]
Thanks! I would like to first move the testing infra from Travis to GitHub Actions, I'll try to find a time for this next week.

**Comment by colans** [comment]
This should now be good to go, assuming all checks are successful.  If you're cool with this, @jnv , this should also close #32.  There's additional discussion in there, but I don't believe it does anything more for us.

(I can't speak to GitHub Actions; we do everything in GitLab.com's CI.  In fact, I haven't even been on GitHub in a while now and it looks like there's no way to refer to an MR in a commit message, or as they call them here, PRs ;)

**Comment by colans** [comment]
@jnv Any chance you can merge this soon, and close #32 ?  Thanks!

**Comment by iamdevnull** [comment]
It would be great if this could be merged plz.

Thx

**Comment by jnv** [comment]
I am closing this PR since this role has been deprecated. Feel free to suggest alternatives in #98.

**Comment by colans** [comment]
I requested that this be merged via the issue in the new project @ https://github.com/hifis-net/ansible-role-unattended-upgrades/issues/10.

**Pull request closed without merging**
