### PR TITLE
Add the battery option

### PR DESCRIPTION
**Pull request by smutel**
Be able to use the unattended-upgrades option called Unattended-Upgrade::OnlyOnACPower with this role.

### CODE REVIEW

**Comment by kousu** [comment]
Nice :)

**Comment by jnv** [comment]
Hi, sorry for ignoring this for such a long time. I am okay with this feature, but it shouldn't be enabled by default – my understanding is unattended-upgrades have `"false"` as the default. The automatic installation of `powermgmt-base` with this option should be documented as well (not sure whether it works cross-distro).

**Comment by smutel** [comment]
Updated regarding your comments.  
For the moment the package is called `powermgmt-base` for all `debian` like distro.

**Comment by jnv** [comment]
Sorry for the delay and thank you @smutel!

**Pull request merged**
