### PR TITLE
Add unattended_verbose (default 0) and unattended_random_sleep (default 1800)

### PR DESCRIPTION
**Pull request by osiris**
Define verbose level APT::Periodic::Verbose

  0:  no report             (or null string)
  1:  progress report       (actually any string)
  2:  + command outputs     (remove -qq, remove 2>/dev/null, add -d)
  3:  + trace on

### CODE REVIEW

**Comment by jnv** [comment]
Thanks for your Pull Request! Could you please add explanation of the configuration to the Readme?

**Comment by osiris** [comment]
Add configuration to the Readme in last commit.

**Comment by jnv** [comment]
Thank you! I was digging through the original configuration and [the source code](https://bazaar.launchpad.net/~unattended-upgrades-developers/unattended-upgrades/trunk/view/head:/unattended-upgrade) of the script, but I can't find this configuration being handled in either place. Are you sure this option is still supported?

**Comment by osiris** [comment]
Sorry for the delay. I can fix the `unattended_verbose` in correct place, and add `unattended_random_sleep`, both are APT Preferences in `/etc/apt/apt.conf.d/20auto-upgrades`

**Comment by jnv** [comment]
I have rolled these changes into the PR #33 which I will work into the next major release. Thank you!

**Pull request closed without merging**
