### PR TITLE
Set IgnoreAppsRequireRestart to TRUE, to avoid restarting  critical apps

### PR DESCRIPTION
**Pull request by bram70**
I am attempting to mimic these changes and apply them in this ansible role.
```
  * unattended-upgrade:
    - Do not upgrade apps if "XB-Upgrade-Requires: app-restart"
      is set in the debian/control file.
      This can be override with the option:
      Unattended-Upgrade::IgnoreAppsRequireRestart=true
```
https://github.com/mvo5/unattended-upgrades/blob/2f2683d6c2065e17379870ef4b366482f3a6c90e/debian/changelog#L806

So we could avoid restarting critical services as this suggests:
``` python
# check if the package is unsafe to upgrade unattended
            ignore_require_restart = apt_pkg.config.find_b(
                "Unattended-Upgrade::IgnoreAppsRequireRestart", False)
            upgrade_requires = pkg.candidate.record.get("Upgrade-Requires")
            if (pkg.marked_upgrade and ignore_require_restart is False and
                    upgrade_requires == "app-restart"):
                logging.debug("pkg '%s' requires app-restart, not safe to "
                              "upgrade unattended")
                return False
```
https://github.com/mvo5/unattended-upgrades/blob/89226202dc10c9aa11881df3ca57986a0d70e224/unattended-upgrade#L572-L579

### CODE REVIEW

**Comment by jnv** [comment]
Thanks! Do you think it would make sense to have this option configurable in the role, or we just roll with defaults?

**Comment by bram70** [comment]
I could elaborate a little bit more and write this as an option from this ansible role. I am going to refactor this.

**Comment by jnv** [comment]
@bram70: Would you still like to take a look at this?

**Comment by bram70** [comment]
I will take a look at this this week. I've been a little bit busy, but I will.

**Comment by jnv** [comment]
No worries, thank you!

**Comment by jnv** [comment]
So, I dug bit deeper into this directive and I think unattended-upgrade's default behaviour is safe, i.e. it won't attempt to upgrade such packages. So I have turned this option off by default.
Committed in 9d534a075a72a25bee42ca69c3eee1ad14fbcc1b

**Pull request closed without merging**
